### ISSUE TITLE
Add description to itemType

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#22]
It's worth considering to add a `description` field to `itemType` so we can have all of the descriptions of items onchain. This would allow developers to easily replicate a marketplace later. Many NFTs have short onchain metadata.

**Comment by mudgen** [comment]
Also add author name of art

**Comment by mudgen** [comment]
I'm leery about adding these just because of the gas cost, but we can do it.

**Comment by mudgen** [comment]
I added author and description to itemType.   These are returned by functions `getItemType` and `getItemTypes`.

The itemType.js file needs to be updated with the author and description for each itemType.

I did not add a size limit to the author and description fields because access to add items is limited to contractOwner and DAO.  However we should try to limit most names and descriptions to 31 characters or less for gas savings.

**Comment by cinnabarhorse** [comment]
Great, this is added but probably won't be used much. Closed.
