### ISSUE TITLE
Possible bug with names not being re-available after being used once

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#69]
We had a user set a name, then change it and try to use it on a different Aavegotchi, but he was unable to do so. I believe this issue was fixed previously but may still exist somehow. Let's verify and fix in an upgrade if possible.

**Comment by mudgen** [comment]
Thanks, I checked it out.    No bug here.  

The name "CASPER THE FRIENDLY GHOST"  name is indeed taken.  Here it is: https://aavegotchi.com/gotchi/1646

This guy never named his gotchi "CASPER THE FRIENDLY GHOST".    He named his gotchi "CASPER THE FRENDLY GHOST"   which is a different name because FRENDLY is spelled different.

Getting the activity log working will help with this stuff so people can see the history of what happened.

**Comment by cinnabarhorse** [comment]
Got it! This is resolved then, thanks for looking into it.
